### PR TITLE
[FIX] Update travis config to test OCA/maintainer-quality-tools#340

### PR DESCRIPTION
**Pull request by lasley**

### CODE REVIEW

**Comment by moylop260** [comment]
lasley

Do you have one forked project with TRANSIFEX enabled?

**Comment by lasley** [comment]
Oops I based on the wrong branch my bad. Rebasing

**Comment by lasley** [comment]
Woot I see what you did now! Looks good, we've got a green light on both the PR and Push build Transifex

**Comment by moylop260** [comment]
Thank you!

**Pull request closed without merging**
